artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rui-2002/
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion